import os

names = [
  "accelerometer",
  "audio_recording",
  "barometer",
  "battery",
  "bluetooth",
  "brightness",
  "call",
  "camera",
  "compass",
  "clipboard",
  "cpu_count",
  "device_name",
  "email",
  "file_chooser",
  "flash",
  "gps",
  "gravity",
  "gyroscope",
  "humidity",
  "ir_blaster",
  "keystore",
  "light",
  "maps",
  "notifications",
  "orientation",
  "proximity",
  "screenshot",
  "sms",
  "spatial_orientation",
  "speech_to_text",
  "storage_path",
  "temperature",
  "text_to_speech",
  "threads",
  "unique_id",
  "vibrator",
  "voip",
  "wifi"
]
upper_names = [n.upper() for n in names]

output = []

for n in upper_names:
    on = [nn for nn in upper_names if n != nn]
    block = [
      f"#ifdef HAL_ONLY_{n}",
      "\n".join([f"#define HAL_NO_{nn}" for nn in on]),
      f"#endif // HAL_ONLY_{n}\n",
    ]
    output.append(block)

for n in upper_names:
    ln = n.lower()
    header = f"\"native/{ln}.h\""
    block = [
      f"#if !defined(HAL_NO_{n}) && __has_include({header})",
      f"#include {header}",
      "#endif"
    ]
    output.append(block)

with open(os.path.join(os.getcwd(), "hal", "hal.h"), "r+") as fh:
    lines = [l.rstrip() for l in fh.readlines()]
    header = []
    footer = []
    state = 0
    for line in lines:
        match state:
            case 0:
                if line == "// BEGIN INCLUDES":
                    state = 1
                header.append(line)
            case 1:
                if line == "// END INCLUDES":
                    state = 2
                    footer.append(line)
            case _:
                footer.append(line)

    fh.seek(0)
    fh.truncate()

    fh.write("\n".join(header) + "\n")
    for block in output:
        fh.write("\n".join(block) + "\n")
    fh.write("\n".join(footer))

print("Generated hal/hal.h")

# Generate CMake module definitions
cmake_output = []
cmake_output.append("# Auto-generated by generate.py - DO NOT EDIT MANUALLY")
cmake_output.append("")
cmake_output.append("# List of all HAL modules")
cmake_output.append("set(HAL_ALL_MODULES")

for name in names:
    cmake_output.append(f"  {name}")

cmake_output.append(")")
cmake_output.append("")
cmake_output.append("# Module enable options (default: all enabled)")

for name in names:
    upper_name = name.upper()
    # Format the description nicely by replacing underscores with spaces
    desc = name.replace("_", " ")
    cmake_output.append(f'option(HAL_ENABLE_{upper_name} "Enable {desc} module" ON)')

cmake_output.append("")

# Create cmake directory if it doesn't exist
cmake_dir = os.path.join(os.getcwd(), "cmake")
os.makedirs(cmake_dir, exist_ok=True)

# Write CMake module file
cmake_file_path = os.path.join(cmake_dir, "HalModules.cmake")
with open(cmake_file_path, "w") as cf:
    cf.write("\n".join(cmake_output) + "\n")

print(f"Generated cmake/HalModules.cmake with {len(names)} modules")
