/* paul.h -- https://github.com/takeiteasy/paul

paul Copyright (C) 2025 George Watson

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>. */

#ifndef PAUL_HEAD
#define PAUL_HEAD
#ifdef __cplusplus
extern "C" {
#endif

#ifdef _MSC_VER
#define COMPILER_CL

#ifdef _WIN32
#define PLATFORM_WINDOWS
#else
#error compiler/platform combo is not supported yet
#endif

#if defined(_M_AMD64)
#define ARCH_X64
#elif defined(_M_IX86)
#define ARCH_X86
#elif defined(_M_ARM64)
#define ARCH_ARM64
#elif defined(_M_ARM)
#define ARCH_ARM32
#else
#error architecture not supported yet
#endif

#if _MSC_VER >= 1920
#define COMPILER_CL_YEAR 2019
#elif _MSC_VER >= 1910
#define COMPILER_CL_YEAR 2017
#elif _MSC_VER >= 1900
#define COMPILER_CL_YEAR 2015
#elif _MSC_VER >= 1800
#define COMPILER_CL_YEAR 2013
#elif _MSC_VER >= 1700
#define COMPILER_CL_YEAR 2012
#elif _MSC_VER >= 1600
#define COMPILER_CL_YEAR 2010
#elif _MSC_VER >= 1500
#define COMPILER_CL_YEAR 2008
#elif _MSC_VER >= 1400
#define COMPILER_CL_YEAR 2005
#else
#define COMPILER_CL_YEAR 0
#endif
// defined(_MSC_VER)
#elif defined(__clang__)
#define COMPILER_CLANG

#if defined(__APPLE__) && defined(__MACH__)
#define PLATFORM_MAC
#elif defined(__gnu_linux__)
#define PLATFORM_LINUX
#else
#error compiler/platform combo is not supported yet
#endif

#if defined(__amd64__) || defined(__amd64) || defined(__x86_64__) || defined(__x86_64)
#define ARCH_X64
#elif defined(i386) || defined(__i386) || defined(__i386__)
#define ARCH_X86
#elif defined(__aarch64__)
#define ARCH_ARM64
#elif defined(__arm__)
#define ARCH_ARM32
#else
#error architecture not supported yet
#endif
// defined(__clang__)
#elif defined(__GNUC__) || defined(__GNUG__)
#define COMPILER_GCC

#ifdef __gnu_linux__
#define PLATFORM_LINUX
#else
#error compiler/platform combo is not supported yet
#endif

#if defined(__amd64__) || defined(__amd64) || defined(__x86_64__) || defined(__x86_64)
#define ARCH_X64
#elif defined(i386) || defined(__i386) || defined(__i386__)
#define ARCH_X86
#elif defined(__aarch64__)
#define ARCH_ARM64
#elif defined(__arm__)
#define ARCH_ARM32
#else
#error architecture not supported yet
#endif
#else
#error compiler is not supported yet
#endif

#if defined(ARCH_X64)
#define ARCH_64BIT
#elif defined(ARCH_X86)
#define ARCH_32BIT
#else
#error architecture not supported yet
#endif

#ifdef __cplusplus
#define LANG_CPP
#else
#define LANG_C
#endif

#ifndef PLATFORM_WINDOWS
#define PLATFORM_POSIX
#endif

#ifndef __has_include
#define __has_include(x) 1
#endif

// BEGIN INCLUDES
#ifdef PAUL_ONLY_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_ACCELEROMETER

#ifdef PAUL_ONLY_AUDIO_RECORDING
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_AUDIO_RECORDING

#ifdef PAUL_ONLY_BAROMETER
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_BAROMETER

#ifdef PAUL_ONLY_BATTERY
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_BATTERY

#ifdef PAUL_ONLY_BLUETOOTH
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_BLUETOOTH

#ifdef PAUL_ONLY_BRIGHTNESS
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_BRIGHTNESS

#ifdef PAUL_ONLY_CALL
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_CALL

#ifdef PAUL_ONLY_CAMERA
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_CAMERA

#ifdef PAUL_ONLY_COMPASS
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_COMPASS

#ifdef PAUL_ONLY_CPU_COUNT
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_CPU_COUNT

#ifdef PAUL_ONLY_DEVICE_NAME
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_DEVICE_NAME

#ifdef PAUL_ONLY_EMAIL
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_EMAIL

#ifdef PAUL_ONLY_FLASH
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_FLASH

#ifdef PAUL_ONLY_GPS
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_GPS

#ifdef PAUL_ONLY_GRAVITY
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_GRAVITY

#ifdef PAUL_ONLY_GYROSCOPE
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_GYROSCOPE

#ifdef PAUL_ONLY_HUMIDITY
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_HUMIDITY

#ifdef PAUL_ONLY_IR_BLASTER
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_IR_BLASTER

#ifdef PAUL_ONLY_KEYSTORE
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_KEYSTORE

#ifdef PAUL_ONLY_LIGHT
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_LIGHT

#ifdef PAUL_ONLY_MAPS
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_MAPS

#ifdef PAUL_ONLY_FILE_CHOOSER
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_FILE_CHOOSER

#ifdef PAUL_ONLY_NOTIFICATIONS
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_NOTIFICATIONS

#ifdef PAUL_ONLY_ORIENTATION
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_ORIENTATION

#ifdef PAUL_ONLY_PROXIMITY
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_PROXIMITY

#ifdef PAUL_ONLY_SCREENSHOT
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_SCREENSHOT

#ifdef PAUL_ONLY_SMS
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_SMS

#ifdef PAUL_ONLY_SPATIAL_ROIENTATION
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_SPATIAL_ROIENTATION

#ifdef PAUL_ONLY_SPEACH_TO_TEXT
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_SPEACH_TO_TEXT

#ifdef PAUL_ONLY_STORAGE_PATH
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_STORAGE_PATH

#ifdef PAUL_ONLY_TEMPERATURE
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_TEMPERATURE

#ifdef PAUL_ONLY_SPEECH_TO_TEXT
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_SPEECH_TO_TEXT

#ifdef PAUL_ONLY_UNIQUE_ID
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_UNIQUE_ID

#ifdef PAUL_ONLY_VIBRATOR
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VOIP
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_VIBRATOR

#ifdef PAUL_ONLY_VOIP
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_WIFI
#endif // PAUL_ONLY_VOIP

#ifdef PAUL_ONLY_WIFI
#define PAUL_NO_ACCELEROMETER
#define PAUL_NO_AUDIO_RECORDING
#define PAUL_NO_BAROMETER
#define PAUL_NO_BATTERY
#define PAUL_NO_BLUETOOTH
#define PAUL_NO_BRIGHTNESS
#define PAUL_NO_CALL
#define PAUL_NO_CAMERA
#define PAUL_NO_COMPASS
#define PAUL_NO_CPU_COUNT
#define PAUL_NO_DEVICE_NAME
#define PAUL_NO_EMAIL
#define PAUL_NO_FLASH
#define PAUL_NO_GPS
#define PAUL_NO_GRAVITY
#define PAUL_NO_GYROSCOPE
#define PAUL_NO_HUMIDITY
#define PAUL_NO_IR_BLASTER
#define PAUL_NO_KEYSTORE
#define PAUL_NO_LIGHT
#define PAUL_NO_MAPS
#define PAUL_NO_FILE_CHOOSER
#define PAUL_NO_NOTIFICATIONS
#define PAUL_NO_ORIENTATION
#define PAUL_NO_PROXIMITY
#define PAUL_NO_SCREENSHOT
#define PAUL_NO_SMS
#define PAUL_NO_SPATIAL_ROIENTATION
#define PAUL_NO_SPEACH_TO_TEXT
#define PAUL_NO_STORAGE_PATH
#define PAUL_NO_TEMPERATURE
#define PAUL_NO_SPEECH_TO_TEXT
#define PAUL_NO_UNIQUE_ID
#define PAUL_NO_VIBRATOR
#define PAUL_NO_VOIP
#endif // PAUL_ONLY_WIFI

#if !defined(PAUL_NO_ACCELEROMETER) && __has_include("native/accelerometer.h")
#include "native/accelerometer.h"
#endif
#if !defined(PAUL_NO_AUDIO_RECORDING) && __has_include("native/audio_recording.h")
#include "native/audio_recording.h"
#endif
#if !defined(PAUL_NO_BAROMETER) && __has_include("native/barometer.h")
#include "native/barometer.h"
#endif
#if !defined(PAUL_NO_BATTERY) && __has_include("native/battery.h")
#include "native/battery.h"
#endif
#if !defined(PAUL_NO_BLUETOOTH) && __has_include("native/bluetooth.h")
#include "native/bluetooth.h"
#endif
#if !defined(PAUL_NO_BRIGHTNESS) && __has_include("native/brightness.h")
#include "native/brightness.h"
#endif
#if !defined(PAUL_NO_CALL) && __has_include("native/call.h")
#include "native/call.h"
#endif
#if !defined(PAUL_NO_CAMERA) && __has_include("native/camera.h")
#include "native/camera.h"
#endif
#if !defined(PAUL_NO_COMPASS) && __has_include("native/compass.h")
#include "native/compass.h"
#endif
#if !defined(PAUL_NO_CPU_COUNT) && __has_include("native/cpu_count.h")
#include "native/cpu_count.h"
#endif
#if !defined(PAUL_NO_DEVICE_NAME) && __has_include("native/device_name.h")
#include "native/device_name.h"
#endif
#if !defined(PAUL_NO_EMAIL) && __has_include("native/email.h")
#include "native/email.h"
#endif
#if !defined(PAUL_NO_FLASH) && __has_include("native/flash.h")
#include "native/flash.h"
#endif
#if !defined(PAUL_NO_GPS) && __has_include("native/gps.h")
#include "native/gps.h"
#endif
#if !defined(PAUL_NO_GRAVITY) && __has_include("native/gravity.h")
#include "native/gravity.h"
#endif
#if !defined(PAUL_NO_GYROSCOPE) && __has_include("native/gyroscope.h")
#include "native/gyroscope.h"
#endif
#if !defined(PAUL_NO_HUMIDITY) && __has_include("native/humidity.h")
#include "native/humidity.h"
#endif
#if !defined(PAUL_NO_IR_BLASTER) && __has_include("native/ir_blaster.h")
#include "native/ir_blaster.h"
#endif
#if !defined(PAUL_NO_KEYSTORE) && __has_include("native/keystore.h")
#include "native/keystore.h"
#endif
#if !defined(PAUL_NO_LIGHT) && __has_include("native/light.h")
#include "native/light.h"
#endif
#if !defined(PAUL_NO_MAPS) && __has_include("native/maps.h")
#include "native/maps.h"
#endif
#if !defined(PAUL_NO_FILE_CHOOSER) && __has_include("native/file_chooser.h")
#include "native/file_chooser.h"
#endif
#if !defined(PAUL_NO_NOTIFICATIONS) && __has_include("native/notifications.h")
#include "native/notifications.h"
#endif
#if !defined(PAUL_NO_ORIENTATION) && __has_include("native/orientation.h")
#include "native/orientation.h"
#endif
#if !defined(PAUL_NO_PROXIMITY) && __has_include("native/proximity.h")
#include "native/proximity.h"
#endif
#if !defined(PAUL_NO_SCREENSHOT) && __has_include("native/screenshot.h")
#include "native/screenshot.h"
#endif
#if !defined(PAUL_NO_SMS) && __has_include("native/sms.h")
#include "native/sms.h"
#endif
#if !defined(PAUL_NO_SPATIAL_ROIENTATION) && __has_include("native/spatial_roientation.h")
#include "native/spatial_roientation.h"
#endif
#if !defined(PAUL_NO_SPEACH_TO_TEXT) && __has_include("native/speach_to_text.h")
#include "native/speach_to_text.h"
#endif
#if !defined(PAUL_NO_STORAGE_PATH) && __has_include("native/storage_path.h")
#include "native/storage_path.h"
#endif
#if !defined(PAUL_NO_TEMPERATURE) && __has_include("native/temperature.h")
#include "native/temperature.h"
#endif
#if !defined(PAUL_NO_SPEECH_TO_TEXT) && __has_include("native/speech_to_text.h")
#include "native/speech_to_text.h"
#endif
#if !defined(PAUL_NO_UNIQUE_ID) && __has_include("native/unique_id.h")
#include "native/unique_id.h"
#endif
#if !defined(PAUL_NO_VIBRATOR) && __has_include("native/vibrator.h")
#include "native/vibrator.h"
#endif
#if !defined(PAUL_NO_VOIP) && __has_include("native/voip.h")
#include "native/voip.h"
#endif
#if !defined(PAUL_NO_WIFI) && __has_include("native/wifi.h")
#include "native/wifi.h"
#endif
// END INCLUDES

#ifdef __cplusplus
}
#endif
#endif // PAUL_HEAD