# Auto-generated by generate.py - DO NOT EDIT MANUALLY

# List of all HAL modules
set(HAL_ALL_MODULES
  accelerometer
  audio_recording
  barometer
  battery
  bluetooth
  brightness
  call
  camera
  compass
  clipboard
  cpu_count
  device_name
  email
  environment
  file_chooser
  filesystem
  flash
  gps
  gravity
  gyroscope
  humidity
  ir_blaster
  keystore
  light
  maps
  notifications
  orientation
  path_utils
  proximity
  screenshot
  shell
  sms
  spatial_orientation
  speech_to_text
  storagepath
  temperature
  text_to_speech
  threads
  unique_id
  vibrator
  voip
  wifi
)

# Module enable options (default: all enabled)
option(HAL_ENABLE_ACCELEROMETER "Enable accelerometer module" ON)
option(HAL_ENABLE_AUDIO_RECORDING "Enable audio recording module" ON)
option(HAL_ENABLE_BAROMETER "Enable barometer module" ON)
option(HAL_ENABLE_BATTERY "Enable battery module" ON)
option(HAL_ENABLE_BLUETOOTH "Enable bluetooth module" ON)
option(HAL_ENABLE_BRIGHTNESS "Enable brightness module" ON)
option(HAL_ENABLE_CALL "Enable call module" ON)
option(HAL_ENABLE_CAMERA "Enable camera module" ON)
option(HAL_ENABLE_COMPASS "Enable compass module" ON)
option(HAL_ENABLE_CLIPBOARD "Enable clipboard module" ON)
option(HAL_ENABLE_CPU_COUNT "Enable cpu count module" ON)
option(HAL_ENABLE_DEVICE_NAME "Enable device name module" ON)
option(HAL_ENABLE_EMAIL "Enable email module" ON)
option(HAL_ENABLE_ENVIRONMENT "Enable environment module" ON)
option(HAL_ENABLE_FILE_CHOOSER "Enable file chooser module" ON)
option(HAL_ENABLE_FILESYSTEM "Enable filesystem module" ON)
option(HAL_ENABLE_FLASH "Enable flash module" ON)
option(HAL_ENABLE_GPS "Enable gps module" ON)
option(HAL_ENABLE_GRAVITY "Enable gravity module" ON)
option(HAL_ENABLE_GYROSCOPE "Enable gyroscope module" ON)
option(HAL_ENABLE_HUMIDITY "Enable humidity module" ON)
option(HAL_ENABLE_IR_BLASTER "Enable ir blaster module" ON)
option(HAL_ENABLE_KEYSTORE "Enable keystore module" ON)
option(HAL_ENABLE_LIGHT "Enable light module" ON)
option(HAL_ENABLE_MAPS "Enable maps module" ON)
option(HAL_ENABLE_NOTIFICATIONS "Enable notifications module" ON)
option(HAL_ENABLE_ORIENTATION "Enable orientation module" ON)
option(HAL_ENABLE_PATH_UTILS "Enable path utils module" ON)
option(HAL_ENABLE_PROXIMITY "Enable proximity module" ON)
option(HAL_ENABLE_SCREENSHOT "Enable screenshot module" ON)
option(HAL_ENABLE_SHELL "Enable shell module" ON)
option(HAL_ENABLE_SMS "Enable sms module" ON)
option(HAL_ENABLE_SPATIAL_ORIENTATION "Enable spatial orientation module" ON)
option(HAL_ENABLE_SPEECH_TO_TEXT "Enable speech to text module" ON)
option(HAL_ENABLE_STORAGEPATH "Enable storagepath module" ON)
option(HAL_ENABLE_TEMPERATURE "Enable temperature module" ON)
option(HAL_ENABLE_TEXT_TO_SPEECH "Enable text to speech module" ON)
option(HAL_ENABLE_THREADS "Enable threads module" ON)
option(HAL_ENABLE_UNIQUE_ID "Enable unique id module" ON)
option(HAL_ENABLE_VIBRATOR "Enable vibrator module" ON)
option(HAL_ENABLE_VOIP "Enable voip module" ON)
option(HAL_ENABLE_WIFI "Enable wifi module" ON)

